import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')

// Config
const childrenDirs = [
  { name: 'evangelina', sourceDir: 'images_rewards/Evangeline' },
  { name: 'noah', sourceDir: 'images_rewards/Noah' },
]
const musicSourceDir = 'music'

const musicTitles = {
  '01': 'Somewhere in My Memory',
  '04': 'Golden',
  '09': 'What It Sounds Like',
  '14': 'Setting the Trap',
}

// --- Images ---
const rewardManifest = {}

for (const child of childrenDirs) {
  const srcDir = path.join(ROOT, child.sourceDir)
  const destDir = path.join(ROOT, 'public', 'rewards', child.name)

  fs.mkdirSync(destDir, { recursive: true })

  // Clean destination
  for (const f of fs.readdirSync(destDir)) {
    fs.unlinkSync(path.join(destDir, f))
  }

  const files = fs.readdirSync(srcDir)
    .filter(f => f.toLowerCase().endsWith('.png'))
    .sort()

  const images = []
  files.forEach((file, i) => {
    const num = String(i + 1).padStart(3, '0')
    const newName = `${child.name}-${num}.png`
    fs.copyFileSync(path.join(srcDir, file), path.join(destDir, newName))
    images.push({ id: `${child.name}-${num}`, src: `/rewards/${child.name}/${newName}` })
  })

  rewardManifest[child.name] = images
  console.log(`[sync-assets] ${child.name}: ${images.length} images copied`)
}

// Generate rewardManifest.ts
const rewardTs = `// AUTO-GENERATED by scripts/sync-assets.js — do not edit manually
export const rewardImagesByChild: Record<string, { id: string; src: string }[]> = ${JSON.stringify(rewardManifest, null, 2)}
`
fs.writeFileSync(path.join(ROOT, 'src', 'data', 'rewardManifest.ts'), rewardTs)
console.log('[sync-assets] src/data/rewardManifest.ts generated')

// --- Music ---
const musicSrcDir = path.join(ROOT, musicSourceDir)
const musicDestDir = path.join(ROOT, 'public', 'music')
fs.mkdirSync(musicDestDir, { recursive: true })

// Clean destination
for (const f of fs.readdirSync(musicDestDir)) {
  fs.unlinkSync(path.join(musicDestDir, f))
}

const musicFiles = fs.readdirSync(musicSrcDir)
  .filter(f => f.toLowerCase().endsWith('.mp3'))
  .sort()

const tracks = []
musicFiles.forEach((file, i) => {
  const num = String(i + 1).padStart(2, '0')
  const newName = `track-${num}.mp3`
  fs.copyFileSync(path.join(musicSrcDir, file), path.join(musicDestDir, newName))

  // Try to extract track number prefix for title lookup
  const trackNum = file.match(/^(\d+)/)?.[1]
  const title = (trackNum && musicTitles[trackNum]) || file.replace('.mp3', '')

  tracks.push({ id: `track-${num}`, src: `/music/${newName}`, title })
})

// Generate musicManifest.ts
const musicTs = `// AUTO-GENERATED by scripts/sync-assets.js — do not edit manually
export const musicTracks: { id: string; src: string; title: string }[] = ${JSON.stringify(tracks, null, 2)}
`
fs.writeFileSync(path.join(ROOT, 'src', 'data', 'musicManifest.ts'), musicTs)
console.log(`[sync-assets] ${tracks.length} music tracks copied`)
console.log('[sync-assets] src/data/musicManifest.ts generated')
console.log('[sync-assets] Done!')
