import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')

// Config — chaque sous-dossier de images_rewards/ devient un pool d'univers.
// Les alias préservent une clé de manifeste historique si elle diffère du slug
// du dossier ; tout nouveau dossier est slugifié automatiquement.
const POOL_KEY_ALIASES = {}

function slugifyPoolKey(folderName) {
  return folderName
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '') // retire les accents
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

const imagesRoot = path.join(ROOT, 'images_rewards')
const childrenDirs = fs.readdirSync(imagesRoot, { withFileTypes: true })
  .filter(entry => entry.isDirectory())
  .map(entry => ({
    name: POOL_KEY_ALIASES[entry.name] ?? slugifyPoolKey(entry.name),
    sourceDir: `images_rewards/${entry.name}`,
  }))
  .sort((a, b) => a.name.localeCompare(b.name))

// Musiques : dossier source vide depuis le retrait des titres stock (02/07/2026).
// Le pipeline reste en place pour les futurs titres originaux (Suno) : déposer
// des .mp3 dans music/ (le nom de fichier devient le titre) puis relancer.
const musicSourceDir = 'music'

// --- Images ---
const rewardManifest = {}

// Purge les pools de destination dont le dossier source a disparu
const rewardsDest = path.join(ROOT, 'public', 'rewards')
if (fs.existsSync(rewardsDest)) {
  const validNames = new Set(childrenDirs.map(c => c.name))
  for (const entry of fs.readdirSync(rewardsDest, { withFileTypes: true })) {
    if (entry.isDirectory() && !validNames.has(entry.name)) {
      fs.rmSync(path.join(rewardsDest, entry.name), { recursive: true })
      console.log(`[sync-assets] ${entry.name}: pool orphelin supprimé de public/rewards`)
    }
  }
}

for (const child of childrenDirs) {
  const srcDir = path.join(ROOT, child.sourceDir)
  const destDir = path.join(ROOT, 'public', 'rewards', child.name)

  fs.mkdirSync(destDir, { recursive: true })

  // Clean destination
  for (const f of fs.readdirSync(destDir)) {
    fs.unlinkSync(path.join(destDir, f))
  }

  const files = fs.readdirSync(srcDir)
    .filter(f => /\.(png|jpe?g|webp)$/i.test(f))
    .sort()

  const images = []
  files.forEach((file, i) => {
    const num = String(i + 1).padStart(3, '0')
    const ext = path.extname(file).toLowerCase().replace('jpeg', 'jpg')
    const newName = `${child.name}-${num}${ext}`
    fs.copyFileSync(path.join(srcDir, file), path.join(destDir, newName))
    images.push({ id: `${child.name}-${num}`, src: `/rewards/${child.name}/${newName}` })
  })

  rewardManifest[child.name] = images
  console.log(`[sync-assets] ${child.name}: ${images.length} images copied`)
}

// Generate rewardManifest.ts
const rewardTs = `// AUTO-GENERATED by scripts/sync-assets.js — do not edit manually
export const rewardImagesByChild: Record<string, { id: string; src: string }[]> = ${JSON.stringify(rewardManifest, null, 2)}
`
fs.writeFileSync(path.join(ROOT, 'src', 'data', 'rewardManifest.ts'), rewardTs)
console.log('[sync-assets] src/data/rewardManifest.ts generated')

// --- Music ---
const musicSrcDir = path.join(ROOT, musicSourceDir)
const musicDestDir = path.join(ROOT, 'public', 'music')
fs.mkdirSync(musicDestDir, { recursive: true })

// Clean destination
for (const f of fs.readdirSync(musicDestDir)) {
  fs.unlinkSync(path.join(musicDestDir, f))
}

const musicFiles = fs.existsSync(musicSrcDir)
  ? fs.readdirSync(musicSrcDir).filter(f => f.toLowerCase().endsWith('.mp3')).sort()
  : []

const tracks = []
musicFiles.forEach((file, i) => {
  const num = String(i + 1).padStart(2, '0')
  const newName = `track-${num}.mp3`
  fs.copyFileSync(path.join(musicSrcDir, file), path.join(musicDestDir, newName))
  tracks.push({ id: `track-${num}`, src: `/music/${newName}`, title: file.replace(/\.mp3$/i, '') })
})

// Generate musicManifest.ts
const musicTs = `// AUTO-GENERATED by scripts/sync-assets.js — do not edit manually
export const musicTracks: { id: string; src: string; title: string }[] = ${JSON.stringify(tracks, null, 2)}
`
fs.writeFileSync(path.join(ROOT, 'src', 'data', 'musicManifest.ts'), musicTs)
console.log(`[sync-assets] ${tracks.length} music tracks copied`)
console.log('[sync-assets] src/data/musicManifest.ts generated')
console.log('[sync-assets] Done!')
