// AUTO-GENERATED by scripts/sync-assets.js — do not edit manually
export const musicTracks: { id: string; src: string; title: string }[] = [
  {
    "id": "track-01",
    "src": "/music/track-01.mp3",
    "title": "Somewhere in My Memory"
  },
  {
    "id": "track-02",
    "src": "/music/track-02.mp3",
    "title": "Golden"
  },
  {
    "id": "track-03",
    "src": "/music/track-03.mp3",
    "title": "What It Sounds Like"
  },
  {
    "id": "track-04",
    "src": "/music/track-04.mp3",
    "title": "Setting the Trap"
  }
]
