// AUTO-GENERATED by scripts/sync-assets.js — do not edit manually
export const rewardImagesByChild: Record<string, { id: string; src: string }[]> = {
  "animaux-imaginaires": [
    {
      "id": "animaux-imaginaires-001",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-001.webp"
    },
    {
      "id": "animaux-imaginaires-002",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-002.webp"
    },
    {
      "id": "animaux-imaginaires-003",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-003.webp"
    },
    {
      "id": "animaux-imaginaires-004",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-004.webp"
    },
    {
      "id": "animaux-imaginaires-005",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-005.webp"
    },
    {
      "id": "animaux-imaginaires-006",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-006.webp"
    },
    {
      "id": "animaux-imaginaires-007",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-007.webp"
    },
    {
      "id": "animaux-imaginaires-008",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-008.webp"
    },
    {
      "id": "animaux-imaginaires-009",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-009.webp"
    },
    {
      "id": "animaux-imaginaires-010",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-010.webp"
    },
    {
      "id": "animaux-imaginaires-011",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-011.webp"
    },
    {
      "id": "animaux-imaginaires-012",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-012.webp"
    },
    {
      "id": "animaux-imaginaires-013",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-013.webp"
    },
    {
      "id": "animaux-imaginaires-014",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-014.webp"
    },
    {
      "id": "animaux-imaginaires-015",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-015.webp"
    },
    {
      "id": "animaux-imaginaires-016",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-016.webp"
    },
    {
      "id": "animaux-imaginaires-017",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-017.webp"
    },
    {
      "id": "animaux-imaginaires-018",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-018.webp"
    },
    {
      "id": "animaux-imaginaires-019",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-019.webp"
    },
    {
      "id": "animaux-imaginaires-020",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-020.webp"
    },
    {
      "id": "animaux-imaginaires-021",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-021.webp"
    },
    {
      "id": "animaux-imaginaires-022",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-022.webp"
    },
    {
      "id": "animaux-imaginaires-023",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-023.webp"
    },
    {
      "id": "animaux-imaginaires-024",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-024.webp"
    },
    {
      "id": "animaux-imaginaires-025",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-025.webp"
    },
    {
      "id": "animaux-imaginaires-026",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-026.webp"
    },
    {
      "id": "animaux-imaginaires-027",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-027.webp"
    },
    {
      "id": "animaux-imaginaires-028",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-028.webp"
    },
    {
      "id": "animaux-imaginaires-029",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-029.webp"
    },
    {
      "id": "animaux-imaginaires-030",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-030.webp"
    }
  ],
  "chiens": [
    {
      "id": "chiens-001",
      "src": "/rewards/chiens/chiens-001.webp"
    },
    {
      "id": "chiens-002",
      "src": "/rewards/chiens/chiens-002.webp"
    },
    {
      "id": "chiens-003",
      "src": "/rewards/chiens/chiens-003.webp"
    },
    {
      "id": "chiens-004",
      "src": "/rewards/chiens/chiens-004.webp"
    },
    {
      "id": "chiens-005",
      "src": "/rewards/chiens/chiens-005.webp"
    },
    {
      "id": "chiens-006",
      "src": "/rewards/chiens/chiens-006.webp"
    },
    {
      "id": "chiens-007",
      "src": "/rewards/chiens/chiens-007.webp"
    },
    {
      "id": "chiens-008",
      "src": "/rewards/chiens/chiens-008.webp"
    },
    {
      "id": "chiens-009",
      "src": "/rewards/chiens/chiens-009.webp"
    },
    {
      "id": "chiens-010",
      "src": "/rewards/chiens/chiens-010.webp"
    },
    {
      "id": "chiens-011",
      "src": "/rewards/chiens/chiens-011.webp"
    },
    {
      "id": "chiens-012",
      "src": "/rewards/chiens/chiens-012.webp"
    },
    {
      "id": "chiens-013",
      "src": "/rewards/chiens/chiens-013.webp"
    },
    {
      "id": "chiens-014",
      "src": "/rewards/chiens/chiens-014.webp"
    },
    {
      "id": "chiens-015",
      "src": "/rewards/chiens/chiens-015.webp"
    },
    {
      "id": "chiens-016",
      "src": "/rewards/chiens/chiens-016.webp"
    },
    {
      "id": "chiens-017",
      "src": "/rewards/chiens/chiens-017.webp"
    },
    {
      "id": "chiens-018",
      "src": "/rewards/chiens/chiens-018.webp"
    },
    {
      "id": "chiens-019",
      "src": "/rewards/chiens/chiens-019.webp"
    },
    {
      "id": "chiens-020",
      "src": "/rewards/chiens/chiens-020.webp"
    },
    {
      "id": "chiens-021",
      "src": "/rewards/chiens/chiens-021.webp"
    },
    {
      "id": "chiens-022",
      "src": "/rewards/chiens/chiens-022.webp"
    },
    {
      "id": "chiens-023",
      "src": "/rewards/chiens/chiens-023.webp"
    },
    {
      "id": "chiens-024",
      "src": "/rewards/chiens/chiens-024.webp"
    },
    {
      "id": "chiens-025",
      "src": "/rewards/chiens/chiens-025.webp"
    },
    {
      "id": "chiens-026",
      "src": "/rewards/chiens/chiens-026.webp"
    },
    {
      "id": "chiens-027",
      "src": "/rewards/chiens/chiens-027.webp"
    },
    {
      "id": "chiens-028",
      "src": "/rewards/chiens/chiens-028.webp"
    },
    {
      "id": "chiens-029",
      "src": "/rewards/chiens/chiens-029.webp"
    },
    {
      "id": "chiens-030",
      "src": "/rewards/chiens/chiens-030.webp"
    }
  ],
  "creatures": [
    {
      "id": "creatures-001",
      "src": "/rewards/creatures/creatures-001.webp"
    },
    {
      "id": "creatures-002",
      "src": "/rewards/creatures/creatures-002.webp"
    },
    {
      "id": "creatures-003",
      "src": "/rewards/creatures/creatures-003.webp"
    },
    {
      "id": "creatures-004",
      "src": "/rewards/creatures/creatures-004.webp"
    },
    {
      "id": "creatures-005",
      "src": "/rewards/creatures/creatures-005.webp"
    },
    {
      "id": "creatures-006",
      "src": "/rewards/creatures/creatures-006.webp"
    },
    {
      "id": "creatures-007",
      "src": "/rewards/creatures/creatures-007.webp"
    },
    {
      "id": "creatures-008",
      "src": "/rewards/creatures/creatures-008.webp"
    },
    {
      "id": "creatures-009",
      "src": "/rewards/creatures/creatures-009.webp"
    },
    {
      "id": "creatures-010",
      "src": "/rewards/creatures/creatures-010.webp"
    },
    {
      "id": "creatures-011",
      "src": "/rewards/creatures/creatures-011.webp"
    },
    {
      "id": "creatures-012",
      "src": "/rewards/creatures/creatures-012.webp"
    },
    {
      "id": "creatures-013",
      "src": "/rewards/creatures/creatures-013.webp"
    },
    {
      "id": "creatures-014",
      "src": "/rewards/creatures/creatures-014.webp"
    },
    {
      "id": "creatures-015",
      "src": "/rewards/creatures/creatures-015.webp"
    },
    {
      "id": "creatures-016",
      "src": "/rewards/creatures/creatures-016.webp"
    },
    {
      "id": "creatures-017",
      "src": "/rewards/creatures/creatures-017.webp"
    },
    {
      "id": "creatures-018",
      "src": "/rewards/creatures/creatures-018.webp"
    },
    {
      "id": "creatures-019",
      "src": "/rewards/creatures/creatures-019.webp"
    },
    {
      "id": "creatures-020",
      "src": "/rewards/creatures/creatures-020.webp"
    },
    {
      "id": "creatures-021",
      "src": "/rewards/creatures/creatures-021.webp"
    },
    {
      "id": "creatures-022",
      "src": "/rewards/creatures/creatures-022.webp"
    },
    {
      "id": "creatures-023",
      "src": "/rewards/creatures/creatures-023.webp"
    },
    {
      "id": "creatures-024",
      "src": "/rewards/creatures/creatures-024.webp"
    },
    {
      "id": "creatures-025",
      "src": "/rewards/creatures/creatures-025.webp"
    },
    {
      "id": "creatures-026",
      "src": "/rewards/creatures/creatures-026.webp"
    },
    {
      "id": "creatures-027",
      "src": "/rewards/creatures/creatures-027.webp"
    },
    {
      "id": "creatures-028",
      "src": "/rewards/creatures/creatures-028.webp"
    },
    {
      "id": "creatures-029",
      "src": "/rewards/creatures/creatures-029.webp"
    },
    {
      "id": "creatures-030",
      "src": "/rewards/creatures/creatures-030.webp"
    }
  ],
  "dinosaures": [
    {
      "id": "dinosaures-001",
      "src": "/rewards/dinosaures/dinosaures-001.webp"
    },
    {
      "id": "dinosaures-002",
      "src": "/rewards/dinosaures/dinosaures-002.webp"
    },
    {
      "id": "dinosaures-003",
      "src": "/rewards/dinosaures/dinosaures-003.webp"
    },
    {
      "id": "dinosaures-004",
      "src": "/rewards/dinosaures/dinosaures-004.webp"
    },
    {
      "id": "dinosaures-005",
      "src": "/rewards/dinosaures/dinosaures-005.webp"
    },
    {
      "id": "dinosaures-006",
      "src": "/rewards/dinosaures/dinosaures-006.webp"
    },
    {
      "id": "dinosaures-007",
      "src": "/rewards/dinosaures/dinosaures-007.webp"
    },
    {
      "id": "dinosaures-008",
      "src": "/rewards/dinosaures/dinosaures-008.webp"
    },
    {
      "id": "dinosaures-009",
      "src": "/rewards/dinosaures/dinosaures-009.webp"
    },
    {
      "id": "dinosaures-010",
      "src": "/rewards/dinosaures/dinosaures-010.webp"
    },
    {
      "id": "dinosaures-011",
      "src": "/rewards/dinosaures/dinosaures-011.webp"
    },
    {
      "id": "dinosaures-012",
      "src": "/rewards/dinosaures/dinosaures-012.webp"
    },
    {
      "id": "dinosaures-013",
      "src": "/rewards/dinosaures/dinosaures-013.webp"
    },
    {
      "id": "dinosaures-014",
      "src": "/rewards/dinosaures/dinosaures-014.webp"
    },
    {
      "id": "dinosaures-015",
      "src": "/rewards/dinosaures/dinosaures-015.webp"
    },
    {
      "id": "dinosaures-016",
      "src": "/rewards/dinosaures/dinosaures-016.webp"
    },
    {
      "id": "dinosaures-017",
      "src": "/rewards/dinosaures/dinosaures-017.webp"
    },
    {
      "id": "dinosaures-018",
      "src": "/rewards/dinosaures/dinosaures-018.webp"
    },
    {
      "id": "dinosaures-019",
      "src": "/rewards/dinosaures/dinosaures-019.webp"
    },
    {
      "id": "dinosaures-020",
      "src": "/rewards/dinosaures/dinosaures-020.webp"
    },
    {
      "id": "dinosaures-021",
      "src": "/rewards/dinosaures/dinosaures-021.webp"
    },
    {
      "id": "dinosaures-022",
      "src": "/rewards/dinosaures/dinosaures-022.webp"
    },
    {
      "id": "dinosaures-023",
      "src": "/rewards/dinosaures/dinosaures-023.webp"
    },
    {
      "id": "dinosaures-024",
      "src": "/rewards/dinosaures/dinosaures-024.webp"
    },
    {
      "id": "dinosaures-025",
      "src": "/rewards/dinosaures/dinosaures-025.webp"
    },
    {
      "id": "dinosaures-026",
      "src": "/rewards/dinosaures/dinosaures-026.webp"
    },
    {
      "id": "dinosaures-027",
      "src": "/rewards/dinosaures/dinosaures-027.webp"
    },
    {
      "id": "dinosaures-028",
      "src": "/rewards/dinosaures/dinosaures-028.webp"
    },
    {
      "id": "dinosaures-029",
      "src": "/rewards/dinosaures/dinosaures-029.webp"
    },
    {
      "id": "dinosaures-030",
      "src": "/rewards/dinosaures/dinosaures-030.webp"
    }
  ],
  "kawaii": [
    {
      "id": "kawaii-001",
      "src": "/rewards/kawaii/kawaii-001.webp"
    },
    {
      "id": "kawaii-002",
      "src": "/rewards/kawaii/kawaii-002.webp"
    },
    {
      "id": "kawaii-003",
      "src": "/rewards/kawaii/kawaii-003.webp"
    },
    {
      "id": "kawaii-004",
      "src": "/rewards/kawaii/kawaii-004.webp"
    },
    {
      "id": "kawaii-005",
      "src": "/rewards/kawaii/kawaii-005.webp"
    },
    {
      "id": "kawaii-006",
      "src": "/rewards/kawaii/kawaii-006.webp"
    },
    {
      "id": "kawaii-007",
      "src": "/rewards/kawaii/kawaii-007.webp"
    },
    {
      "id": "kawaii-008",
      "src": "/rewards/kawaii/kawaii-008.webp"
    },
    {
      "id": "kawaii-009",
      "src": "/rewards/kawaii/kawaii-009.webp"
    },
    {
      "id": "kawaii-010",
      "src": "/rewards/kawaii/kawaii-010.webp"
    },
    {
      "id": "kawaii-011",
      "src": "/rewards/kawaii/kawaii-011.webp"
    },
    {
      "id": "kawaii-012",
      "src": "/rewards/kawaii/kawaii-012.webp"
    },
    {
      "id": "kawaii-013",
      "src": "/rewards/kawaii/kawaii-013.webp"
    },
    {
      "id": "kawaii-014",
      "src": "/rewards/kawaii/kawaii-014.webp"
    },
    {
      "id": "kawaii-015",
      "src": "/rewards/kawaii/kawaii-015.webp"
    },
    {
      "id": "kawaii-016",
      "src": "/rewards/kawaii/kawaii-016.webp"
    },
    {
      "id": "kawaii-017",
      "src": "/rewards/kawaii/kawaii-017.webp"
    },
    {
      "id": "kawaii-018",
      "src": "/rewards/kawaii/kawaii-018.webp"
    },
    {
      "id": "kawaii-019",
      "src": "/rewards/kawaii/kawaii-019.webp"
    },
    {
      "id": "kawaii-020",
      "src": "/rewards/kawaii/kawaii-020.webp"
    },
    {
      "id": "kawaii-021",
      "src": "/rewards/kawaii/kawaii-021.webp"
    },
    {
      "id": "kawaii-022",
      "src": "/rewards/kawaii/kawaii-022.webp"
    },
    {
      "id": "kawaii-023",
      "src": "/rewards/kawaii/kawaii-023.webp"
    },
    {
      "id": "kawaii-024",
      "src": "/rewards/kawaii/kawaii-024.webp"
    },
    {
      "id": "kawaii-025",
      "src": "/rewards/kawaii/kawaii-025.webp"
    },
    {
      "id": "kawaii-026",
      "src": "/rewards/kawaii/kawaii-026.webp"
    },
    {
      "id": "kawaii-027",
      "src": "/rewards/kawaii/kawaii-027.webp"
    },
    {
      "id": "kawaii-028",
      "src": "/rewards/kawaii/kawaii-028.webp"
    },
    {
      "id": "kawaii-029",
      "src": "/rewards/kawaii/kawaii-029.webp"
    },
    {
      "id": "kawaii-030",
      "src": "/rewards/kawaii/kawaii-030.webp"
    }
  ],
  "kpop": [
    {
      "id": "kpop-001",
      "src": "/rewards/kpop/kpop-001.webp"
    },
    {
      "id": "kpop-002",
      "src": "/rewards/kpop/kpop-002.webp"
    },
    {
      "id": "kpop-003",
      "src": "/rewards/kpop/kpop-003.webp"
    },
    {
      "id": "kpop-004",
      "src": "/rewards/kpop/kpop-004.webp"
    },
    {
      "id": "kpop-005",
      "src": "/rewards/kpop/kpop-005.webp"
    },
    {
      "id": "kpop-006",
      "src": "/rewards/kpop/kpop-006.webp"
    },
    {
      "id": "kpop-007",
      "src": "/rewards/kpop/kpop-007.webp"
    },
    {
      "id": "kpop-008",
      "src": "/rewards/kpop/kpop-008.webp"
    },
    {
      "id": "kpop-009",
      "src": "/rewards/kpop/kpop-009.webp"
    },
    {
      "id": "kpop-010",
      "src": "/rewards/kpop/kpop-010.webp"
    },
    {
      "id": "kpop-011",
      "src": "/rewards/kpop/kpop-011.webp"
    },
    {
      "id": "kpop-012",
      "src": "/rewards/kpop/kpop-012.webp"
    },
    {
      "id": "kpop-013",
      "src": "/rewards/kpop/kpop-013.webp"
    },
    {
      "id": "kpop-014",
      "src": "/rewards/kpop/kpop-014.webp"
    },
    {
      "id": "kpop-015",
      "src": "/rewards/kpop/kpop-015.webp"
    },
    {
      "id": "kpop-016",
      "src": "/rewards/kpop/kpop-016.webp"
    },
    {
      "id": "kpop-017",
      "src": "/rewards/kpop/kpop-017.webp"
    },
    {
      "id": "kpop-018",
      "src": "/rewards/kpop/kpop-018.webp"
    },
    {
      "id": "kpop-019",
      "src": "/rewards/kpop/kpop-019.webp"
    },
    {
      "id": "kpop-020",
      "src": "/rewards/kpop/kpop-020.webp"
    },
    {
      "id": "kpop-021",
      "src": "/rewards/kpop/kpop-021.webp"
    },
    {
      "id": "kpop-022",
      "src": "/rewards/kpop/kpop-022.webp"
    },
    {
      "id": "kpop-023",
      "src": "/rewards/kpop/kpop-023.webp"
    },
    {
      "id": "kpop-024",
      "src": "/rewards/kpop/kpop-024.webp"
    },
    {
      "id": "kpop-025",
      "src": "/rewards/kpop/kpop-025.webp"
    },
    {
      "id": "kpop-026",
      "src": "/rewards/kpop/kpop-026.webp"
    },
    {
      "id": "kpop-027",
      "src": "/rewards/kpop/kpop-027.webp"
    },
    {
      "id": "kpop-028",
      "src": "/rewards/kpop/kpop-028.webp"
    },
    {
      "id": "kpop-029",
      "src": "/rewards/kpop/kpop-029.webp"
    },
    {
      "id": "kpop-030",
      "src": "/rewards/kpop/kpop-030.webp"
    }
  ],
  "papeterie": [
    {
      "id": "papeterie-001",
      "src": "/rewards/papeterie/papeterie-001.webp"
    },
    {
      "id": "papeterie-002",
      "src": "/rewards/papeterie/papeterie-002.webp"
    },
    {
      "id": "papeterie-003",
      "src": "/rewards/papeterie/papeterie-003.webp"
    },
    {
      "id": "papeterie-004",
      "src": "/rewards/papeterie/papeterie-004.webp"
    },
    {
      "id": "papeterie-005",
      "src": "/rewards/papeterie/papeterie-005.webp"
    },
    {
      "id": "papeterie-006",
      "src": "/rewards/papeterie/papeterie-006.webp"
    },
    {
      "id": "papeterie-007",
      "src": "/rewards/papeterie/papeterie-007.webp"
    },
    {
      "id": "papeterie-008",
      "src": "/rewards/papeterie/papeterie-008.webp"
    },
    {
      "id": "papeterie-009",
      "src": "/rewards/papeterie/papeterie-009.webp"
    },
    {
      "id": "papeterie-010",
      "src": "/rewards/papeterie/papeterie-010.webp"
    },
    {
      "id": "papeterie-011",
      "src": "/rewards/papeterie/papeterie-011.webp"
    },
    {
      "id": "papeterie-012",
      "src": "/rewards/papeterie/papeterie-012.webp"
    },
    {
      "id": "papeterie-013",
      "src": "/rewards/papeterie/papeterie-013.webp"
    },
    {
      "id": "papeterie-014",
      "src": "/rewards/papeterie/papeterie-014.webp"
    },
    {
      "id": "papeterie-015",
      "src": "/rewards/papeterie/papeterie-015.webp"
    },
    {
      "id": "papeterie-016",
      "src": "/rewards/papeterie/papeterie-016.webp"
    },
    {
      "id": "papeterie-017",
      "src": "/rewards/papeterie/papeterie-017.webp"
    },
    {
      "id": "papeterie-018",
      "src": "/rewards/papeterie/papeterie-018.webp"
    },
    {
      "id": "papeterie-019",
      "src": "/rewards/papeterie/papeterie-019.webp"
    },
    {
      "id": "papeterie-020",
      "src": "/rewards/papeterie/papeterie-020.webp"
    },
    {
      "id": "papeterie-021",
      "src": "/rewards/papeterie/papeterie-021.webp"
    },
    {
      "id": "papeterie-022",
      "src": "/rewards/papeterie/papeterie-022.webp"
    },
    {
      "id": "papeterie-023",
      "src": "/rewards/papeterie/papeterie-023.webp"
    },
    {
      "id": "papeterie-024",
      "src": "/rewards/papeterie/papeterie-024.webp"
    },
    {
      "id": "papeterie-025",
      "src": "/rewards/papeterie/papeterie-025.webp"
    },
    {
      "id": "papeterie-026",
      "src": "/rewards/papeterie/papeterie-026.webp"
    },
    {
      "id": "papeterie-027",
      "src": "/rewards/papeterie/papeterie-027.webp"
    },
    {
      "id": "papeterie-028",
      "src": "/rewards/papeterie/papeterie-028.webp"
    },
    {
      "id": "papeterie-029",
      "src": "/rewards/papeterie/papeterie-029.webp"
    },
    {
      "id": "papeterie-030",
      "src": "/rewards/papeterie/papeterie-030.webp"
    }
  ],
  "super-heros": [
    {
      "id": "super-heros-001",
      "src": "/rewards/super-heros/super-heros-001.webp"
    },
    {
      "id": "super-heros-002",
      "src": "/rewards/super-heros/super-heros-002.webp"
    },
    {
      "id": "super-heros-003",
      "src": "/rewards/super-heros/super-heros-003.webp"
    },
    {
      "id": "super-heros-004",
      "src": "/rewards/super-heros/super-heros-004.webp"
    },
    {
      "id": "super-heros-005",
      "src": "/rewards/super-heros/super-heros-005.webp"
    },
    {
      "id": "super-heros-006",
      "src": "/rewards/super-heros/super-heros-006.webp"
    },
    {
      "id": "super-heros-007",
      "src": "/rewards/super-heros/super-heros-007.webp"
    },
    {
      "id": "super-heros-008",
      "src": "/rewards/super-heros/super-heros-008.webp"
    },
    {
      "id": "super-heros-009",
      "src": "/rewards/super-heros/super-heros-009.webp"
    },
    {
      "id": "super-heros-010",
      "src": "/rewards/super-heros/super-heros-010.webp"
    },
    {
      "id": "super-heros-011",
      "src": "/rewards/super-heros/super-heros-011.webp"
    },
    {
      "id": "super-heros-012",
      "src": "/rewards/super-heros/super-heros-012.webp"
    },
    {
      "id": "super-heros-013",
      "src": "/rewards/super-heros/super-heros-013.webp"
    },
    {
      "id": "super-heros-014",
      "src": "/rewards/super-heros/super-heros-014.webp"
    },
    {
      "id": "super-heros-015",
      "src": "/rewards/super-heros/super-heros-015.webp"
    },
    {
      "id": "super-heros-016",
      "src": "/rewards/super-heros/super-heros-016.webp"
    },
    {
      "id": "super-heros-017",
      "src": "/rewards/super-heros/super-heros-017.webp"
    },
    {
      "id": "super-heros-018",
      "src": "/rewards/super-heros/super-heros-018.webp"
    },
    {
      "id": "super-heros-019",
      "src": "/rewards/super-heros/super-heros-019.webp"
    },
    {
      "id": "super-heros-020",
      "src": "/rewards/super-heros/super-heros-020.webp"
    },
    {
      "id": "super-heros-021",
      "src": "/rewards/super-heros/super-heros-021.webp"
    },
    {
      "id": "super-heros-022",
      "src": "/rewards/super-heros/super-heros-022.webp"
    },
    {
      "id": "super-heros-023",
      "src": "/rewards/super-heros/super-heros-023.webp"
    },
    {
      "id": "super-heros-024",
      "src": "/rewards/super-heros/super-heros-024.webp"
    },
    {
      "id": "super-heros-025",
      "src": "/rewards/super-heros/super-heros-025.webp"
    },
    {
      "id": "super-heros-026",
      "src": "/rewards/super-heros/super-heros-026.webp"
    },
    {
      "id": "super-heros-027",
      "src": "/rewards/super-heros/super-heros-027.webp"
    },
    {
      "id": "super-heros-028",
      "src": "/rewards/super-heros/super-heros-028.webp"
    },
    {
      "id": "super-heros-029",
      "src": "/rewards/super-heros/super-heros-029.webp"
    },
    {
      "id": "super-heros-030",
      "src": "/rewards/super-heros/super-heros-030.webp"
    }
  ]
}
