// AUTO-GENERATED by scripts/sync-assets.js — do not edit manually
export const rewardImagesByChild: Record<string, { id: string; src: string }[]> = {
  "animaux-imaginaires": [
    {
      "id": "animaux-imaginaires-001",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-001.webp"
    },
    {
      "id": "animaux-imaginaires-002",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-002.webp"
    },
    {
      "id": "animaux-imaginaires-003",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-003.webp"
    },
    {
      "id": "animaux-imaginaires-004",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-004.webp"
    },
    {
      "id": "animaux-imaginaires-005",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-005.webp"
    },
    {
      "id": "animaux-imaginaires-006",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-006.webp"
    },
    {
      "id": "animaux-imaginaires-007",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-007.webp"
    },
    {
      "id": "animaux-imaginaires-008",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-008.webp"
    },
    {
      "id": "animaux-imaginaires-009",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-009.webp"
    },
    {
      "id": "animaux-imaginaires-010",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-010.webp"
    },
    {
      "id": "animaux-imaginaires-011",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-011.webp"
    },
    {
      "id": "animaux-imaginaires-012",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-012.webp"
    },
    {
      "id": "animaux-imaginaires-013",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-013.webp"
    },
    {
      "id": "animaux-imaginaires-014",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-014.webp"
    },
    {
      "id": "animaux-imaginaires-015",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-015.webp"
    },
    {
      "id": "animaux-imaginaires-016",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-016.webp"
    },
    {
      "id": "animaux-imaginaires-017",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-017.webp"
    },
    {
      "id": "animaux-imaginaires-018",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-018.webp"
    },
    {
      "id": "animaux-imaginaires-019",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-019.webp"
    },
    {
      "id": "animaux-imaginaires-020",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-020.webp"
    },
    {
      "id": "animaux-imaginaires-021",
      "src": "/rewards/animaux-imaginaires/animaux-imaginaires-021.webp"
    }
  ],
  "chiens": [
    {
      "id": "chiens-001",
      "src": "/rewards/chiens/chiens-001.webp"
    },
    {
      "id": "chiens-002",
      "src": "/rewards/chiens/chiens-002.webp"
    },
    {
      "id": "chiens-003",
      "src": "/rewards/chiens/chiens-003.webp"
    },
    {
      "id": "chiens-004",
      "src": "/rewards/chiens/chiens-004.webp"
    },
    {
      "id": "chiens-005",
      "src": "/rewards/chiens/chiens-005.webp"
    },
    {
      "id": "chiens-006",
      "src": "/rewards/chiens/chiens-006.webp"
    },
    {
      "id": "chiens-007",
      "src": "/rewards/chiens/chiens-007.webp"
    },
    {
      "id": "chiens-008",
      "src": "/rewards/chiens/chiens-008.webp"
    },
    {
      "id": "chiens-009",
      "src": "/rewards/chiens/chiens-009.webp"
    },
    {
      "id": "chiens-010",
      "src": "/rewards/chiens/chiens-010.webp"
    },
    {
      "id": "chiens-011",
      "src": "/rewards/chiens/chiens-011.webp"
    },
    {
      "id": "chiens-012",
      "src": "/rewards/chiens/chiens-012.webp"
    },
    {
      "id": "chiens-013",
      "src": "/rewards/chiens/chiens-013.webp"
    },
    {
      "id": "chiens-014",
      "src": "/rewards/chiens/chiens-014.webp"
    },
    {
      "id": "chiens-015",
      "src": "/rewards/chiens/chiens-015.webp"
    },
    {
      "id": "chiens-016",
      "src": "/rewards/chiens/chiens-016.webp"
    },
    {
      "id": "chiens-017",
      "src": "/rewards/chiens/chiens-017.webp"
    },
    {
      "id": "chiens-018",
      "src": "/rewards/chiens/chiens-018.webp"
    },
    {
      "id": "chiens-019",
      "src": "/rewards/chiens/chiens-019.webp"
    },
    {
      "id": "chiens-020",
      "src": "/rewards/chiens/chiens-020.webp"
    },
    {
      "id": "chiens-021",
      "src": "/rewards/chiens/chiens-021.webp"
    },
    {
      "id": "chiens-022",
      "src": "/rewards/chiens/chiens-022.webp"
    },
    {
      "id": "chiens-023",
      "src": "/rewards/chiens/chiens-023.webp"
    },
    {
      "id": "chiens-024",
      "src": "/rewards/chiens/chiens-024.webp"
    },
    {
      "id": "chiens-025",
      "src": "/rewards/chiens/chiens-025.webp"
    },
    {
      "id": "chiens-026",
      "src": "/rewards/chiens/chiens-026.webp"
    },
    {
      "id": "chiens-027",
      "src": "/rewards/chiens/chiens-027.webp"
    },
    {
      "id": "chiens-028",
      "src": "/rewards/chiens/chiens-028.webp"
    },
    {
      "id": "chiens-029",
      "src": "/rewards/chiens/chiens-029.webp"
    },
    {
      "id": "chiens-030",
      "src": "/rewards/chiens/chiens-030.webp"
    }
  ],
  "evangelina": [
    {
      "id": "evangelina-001",
      "src": "/rewards/evangelina/evangelina-001.png"
    },
    {
      "id": "evangelina-002",
      "src": "/rewards/evangelina/evangelina-002.png"
    },
    {
      "id": "evangelina-003",
      "src": "/rewards/evangelina/evangelina-003.png"
    },
    {
      "id": "evangelina-004",
      "src": "/rewards/evangelina/evangelina-004.png"
    },
    {
      "id": "evangelina-005",
      "src": "/rewards/evangelina/evangelina-005.png"
    },
    {
      "id": "evangelina-006",
      "src": "/rewards/evangelina/evangelina-006.png"
    },
    {
      "id": "evangelina-007",
      "src": "/rewards/evangelina/evangelina-007.png"
    },
    {
      "id": "evangelina-008",
      "src": "/rewards/evangelina/evangelina-008.png"
    },
    {
      "id": "evangelina-009",
      "src": "/rewards/evangelina/evangelina-009.png"
    },
    {
      "id": "evangelina-010",
      "src": "/rewards/evangelina/evangelina-010.png"
    },
    {
      "id": "evangelina-011",
      "src": "/rewards/evangelina/evangelina-011.png"
    },
    {
      "id": "evangelina-012",
      "src": "/rewards/evangelina/evangelina-012.png"
    },
    {
      "id": "evangelina-013",
      "src": "/rewards/evangelina/evangelina-013.png"
    },
    {
      "id": "evangelina-014",
      "src": "/rewards/evangelina/evangelina-014.png"
    },
    {
      "id": "evangelina-015",
      "src": "/rewards/evangelina/evangelina-015.png"
    },
    {
      "id": "evangelina-016",
      "src": "/rewards/evangelina/evangelina-016.png"
    },
    {
      "id": "evangelina-017",
      "src": "/rewards/evangelina/evangelina-017.png"
    },
    {
      "id": "evangelina-018",
      "src": "/rewards/evangelina/evangelina-018.png"
    },
    {
      "id": "evangelina-019",
      "src": "/rewards/evangelina/evangelina-019.png"
    },
    {
      "id": "evangelina-020",
      "src": "/rewards/evangelina/evangelina-020.png"
    },
    {
      "id": "evangelina-021",
      "src": "/rewards/evangelina/evangelina-021.png"
    },
    {
      "id": "evangelina-022",
      "src": "/rewards/evangelina/evangelina-022.png"
    },
    {
      "id": "evangelina-023",
      "src": "/rewards/evangelina/evangelina-023.png"
    },
    {
      "id": "evangelina-024",
      "src": "/rewards/evangelina/evangelina-024.png"
    },
    {
      "id": "evangelina-025",
      "src": "/rewards/evangelina/evangelina-025.png"
    },
    {
      "id": "evangelina-026",
      "src": "/rewards/evangelina/evangelina-026.png"
    },
    {
      "id": "evangelina-027",
      "src": "/rewards/evangelina/evangelina-027.png"
    },
    {
      "id": "evangelina-028",
      "src": "/rewards/evangelina/evangelina-028.png"
    },
    {
      "id": "evangelina-029",
      "src": "/rewards/evangelina/evangelina-029.png"
    },
    {
      "id": "evangelina-030",
      "src": "/rewards/evangelina/evangelina-030.png"
    },
    {
      "id": "evangelina-031",
      "src": "/rewards/evangelina/evangelina-031.png"
    },
    {
      "id": "evangelina-032",
      "src": "/rewards/evangelina/evangelina-032.png"
    },
    {
      "id": "evangelina-033",
      "src": "/rewards/evangelina/evangelina-033.png"
    },
    {
      "id": "evangelina-034",
      "src": "/rewards/evangelina/evangelina-034.png"
    },
    {
      "id": "evangelina-035",
      "src": "/rewards/evangelina/evangelina-035.png"
    },
    {
      "id": "evangelina-036",
      "src": "/rewards/evangelina/evangelina-036.png"
    },
    {
      "id": "evangelina-037",
      "src": "/rewards/evangelina/evangelina-037.png"
    },
    {
      "id": "evangelina-038",
      "src": "/rewards/evangelina/evangelina-038.png"
    },
    {
      "id": "evangelina-039",
      "src": "/rewards/evangelina/evangelina-039.png"
    },
    {
      "id": "evangelina-040",
      "src": "/rewards/evangelina/evangelina-040.png"
    },
    {
      "id": "evangelina-041",
      "src": "/rewards/evangelina/evangelina-041.png"
    },
    {
      "id": "evangelina-042",
      "src": "/rewards/evangelina/evangelina-042.png"
    },
    {
      "id": "evangelina-043",
      "src": "/rewards/evangelina/evangelina-043.png"
    },
    {
      "id": "evangelina-044",
      "src": "/rewards/evangelina/evangelina-044.png"
    },
    {
      "id": "evangelina-045",
      "src": "/rewards/evangelina/evangelina-045.png"
    },
    {
      "id": "evangelina-046",
      "src": "/rewards/evangelina/evangelina-046.png"
    },
    {
      "id": "evangelina-047",
      "src": "/rewards/evangelina/evangelina-047.png"
    },
    {
      "id": "evangelina-048",
      "src": "/rewards/evangelina/evangelina-048.png"
    },
    {
      "id": "evangelina-049",
      "src": "/rewards/evangelina/evangelina-049.png"
    },
    {
      "id": "evangelina-050",
      "src": "/rewards/evangelina/evangelina-050.png"
    },
    {
      "id": "evangelina-051",
      "src": "/rewards/evangelina/evangelina-051.png"
    },
    {
      "id": "evangelina-052",
      "src": "/rewards/evangelina/evangelina-052.png"
    }
  ],
  "kawaii": [
    {
      "id": "kawaii-001",
      "src": "/rewards/kawaii/kawaii-001.webp"
    },
    {
      "id": "kawaii-002",
      "src": "/rewards/kawaii/kawaii-002.webp"
    },
    {
      "id": "kawaii-003",
      "src": "/rewards/kawaii/kawaii-003.webp"
    },
    {
      "id": "kawaii-004",
      "src": "/rewards/kawaii/kawaii-004.webp"
    },
    {
      "id": "kawaii-005",
      "src": "/rewards/kawaii/kawaii-005.webp"
    },
    {
      "id": "kawaii-006",
      "src": "/rewards/kawaii/kawaii-006.webp"
    },
    {
      "id": "kawaii-007",
      "src": "/rewards/kawaii/kawaii-007.webp"
    },
    {
      "id": "kawaii-008",
      "src": "/rewards/kawaii/kawaii-008.webp"
    },
    {
      "id": "kawaii-009",
      "src": "/rewards/kawaii/kawaii-009.webp"
    },
    {
      "id": "kawaii-010",
      "src": "/rewards/kawaii/kawaii-010.webp"
    },
    {
      "id": "kawaii-011",
      "src": "/rewards/kawaii/kawaii-011.webp"
    },
    {
      "id": "kawaii-012",
      "src": "/rewards/kawaii/kawaii-012.webp"
    },
    {
      "id": "kawaii-013",
      "src": "/rewards/kawaii/kawaii-013.webp"
    },
    {
      "id": "kawaii-014",
      "src": "/rewards/kawaii/kawaii-014.webp"
    },
    {
      "id": "kawaii-015",
      "src": "/rewards/kawaii/kawaii-015.webp"
    },
    {
      "id": "kawaii-016",
      "src": "/rewards/kawaii/kawaii-016.webp"
    },
    {
      "id": "kawaii-017",
      "src": "/rewards/kawaii/kawaii-017.webp"
    },
    {
      "id": "kawaii-018",
      "src": "/rewards/kawaii/kawaii-018.webp"
    },
    {
      "id": "kawaii-019",
      "src": "/rewards/kawaii/kawaii-019.webp"
    },
    {
      "id": "kawaii-020",
      "src": "/rewards/kawaii/kawaii-020.webp"
    },
    {
      "id": "kawaii-021",
      "src": "/rewards/kawaii/kawaii-021.webp"
    },
    {
      "id": "kawaii-022",
      "src": "/rewards/kawaii/kawaii-022.webp"
    },
    {
      "id": "kawaii-023",
      "src": "/rewards/kawaii/kawaii-023.webp"
    },
    {
      "id": "kawaii-024",
      "src": "/rewards/kawaii/kawaii-024.webp"
    },
    {
      "id": "kawaii-025",
      "src": "/rewards/kawaii/kawaii-025.webp"
    },
    {
      "id": "kawaii-026",
      "src": "/rewards/kawaii/kawaii-026.webp"
    },
    {
      "id": "kawaii-027",
      "src": "/rewards/kawaii/kawaii-027.webp"
    },
    {
      "id": "kawaii-028",
      "src": "/rewards/kawaii/kawaii-028.webp"
    },
    {
      "id": "kawaii-029",
      "src": "/rewards/kawaii/kawaii-029.webp"
    },
    {
      "id": "kawaii-030",
      "src": "/rewards/kawaii/kawaii-030.webp"
    }
  ],
  "kpop": [
    {
      "id": "kpop-001",
      "src": "/rewards/kpop/kpop-001.webp"
    },
    {
      "id": "kpop-002",
      "src": "/rewards/kpop/kpop-002.webp"
    },
    {
      "id": "kpop-003",
      "src": "/rewards/kpop/kpop-003.webp"
    },
    {
      "id": "kpop-004",
      "src": "/rewards/kpop/kpop-004.webp"
    },
    {
      "id": "kpop-005",
      "src": "/rewards/kpop/kpop-005.webp"
    },
    {
      "id": "kpop-006",
      "src": "/rewards/kpop/kpop-006.webp"
    },
    {
      "id": "kpop-007",
      "src": "/rewards/kpop/kpop-007.webp"
    },
    {
      "id": "kpop-008",
      "src": "/rewards/kpop/kpop-008.webp"
    },
    {
      "id": "kpop-009",
      "src": "/rewards/kpop/kpop-009.webp"
    },
    {
      "id": "kpop-010",
      "src": "/rewards/kpop/kpop-010.webp"
    },
    {
      "id": "kpop-011",
      "src": "/rewards/kpop/kpop-011.webp"
    },
    {
      "id": "kpop-012",
      "src": "/rewards/kpop/kpop-012.webp"
    },
    {
      "id": "kpop-013",
      "src": "/rewards/kpop/kpop-013.webp"
    },
    {
      "id": "kpop-014",
      "src": "/rewards/kpop/kpop-014.webp"
    },
    {
      "id": "kpop-015",
      "src": "/rewards/kpop/kpop-015.webp"
    },
    {
      "id": "kpop-016",
      "src": "/rewards/kpop/kpop-016.webp"
    },
    {
      "id": "kpop-017",
      "src": "/rewards/kpop/kpop-017.webp"
    },
    {
      "id": "kpop-018",
      "src": "/rewards/kpop/kpop-018.webp"
    },
    {
      "id": "kpop-019",
      "src": "/rewards/kpop/kpop-019.webp"
    },
    {
      "id": "kpop-020",
      "src": "/rewards/kpop/kpop-020.webp"
    },
    {
      "id": "kpop-021",
      "src": "/rewards/kpop/kpop-021.webp"
    },
    {
      "id": "kpop-022",
      "src": "/rewards/kpop/kpop-022.webp"
    },
    {
      "id": "kpop-023",
      "src": "/rewards/kpop/kpop-023.webp"
    },
    {
      "id": "kpop-024",
      "src": "/rewards/kpop/kpop-024.webp"
    },
    {
      "id": "kpop-025",
      "src": "/rewards/kpop/kpop-025.webp"
    },
    {
      "id": "kpop-026",
      "src": "/rewards/kpop/kpop-026.webp"
    },
    {
      "id": "kpop-027",
      "src": "/rewards/kpop/kpop-027.webp"
    },
    {
      "id": "kpop-028",
      "src": "/rewards/kpop/kpop-028.webp"
    },
    {
      "id": "kpop-029",
      "src": "/rewards/kpop/kpop-029.webp"
    },
    {
      "id": "kpop-030",
      "src": "/rewards/kpop/kpop-030.webp"
    }
  ],
  "noah": [
    {
      "id": "noah-001",
      "src": "/rewards/noah/noah-001.png"
    },
    {
      "id": "noah-002",
      "src": "/rewards/noah/noah-002.png"
    },
    {
      "id": "noah-003",
      "src": "/rewards/noah/noah-003.png"
    },
    {
      "id": "noah-004",
      "src": "/rewards/noah/noah-004.png"
    },
    {
      "id": "noah-005",
      "src": "/rewards/noah/noah-005.png"
    },
    {
      "id": "noah-006",
      "src": "/rewards/noah/noah-006.png"
    },
    {
      "id": "noah-007",
      "src": "/rewards/noah/noah-007.png"
    },
    {
      "id": "noah-008",
      "src": "/rewards/noah/noah-008.png"
    },
    {
      "id": "noah-009",
      "src": "/rewards/noah/noah-009.png"
    },
    {
      "id": "noah-010",
      "src": "/rewards/noah/noah-010.png"
    },
    {
      "id": "noah-011",
      "src": "/rewards/noah/noah-011.png"
    },
    {
      "id": "noah-012",
      "src": "/rewards/noah/noah-012.png"
    },
    {
      "id": "noah-013",
      "src": "/rewards/noah/noah-013.png"
    },
    {
      "id": "noah-014",
      "src": "/rewards/noah/noah-014.png"
    },
    {
      "id": "noah-015",
      "src": "/rewards/noah/noah-015.png"
    },
    {
      "id": "noah-016",
      "src": "/rewards/noah/noah-016.png"
    },
    {
      "id": "noah-017",
      "src": "/rewards/noah/noah-017.png"
    },
    {
      "id": "noah-018",
      "src": "/rewards/noah/noah-018.png"
    },
    {
      "id": "noah-019",
      "src": "/rewards/noah/noah-019.png"
    },
    {
      "id": "noah-020",
      "src": "/rewards/noah/noah-020.png"
    },
    {
      "id": "noah-021",
      "src": "/rewards/noah/noah-021.png"
    },
    {
      "id": "noah-022",
      "src": "/rewards/noah/noah-022.png"
    },
    {
      "id": "noah-023",
      "src": "/rewards/noah/noah-023.png"
    },
    {
      "id": "noah-024",
      "src": "/rewards/noah/noah-024.png"
    },
    {
      "id": "noah-025",
      "src": "/rewards/noah/noah-025.png"
    },
    {
      "id": "noah-026",
      "src": "/rewards/noah/noah-026.png"
    },
    {
      "id": "noah-027",
      "src": "/rewards/noah/noah-027.png"
    },
    {
      "id": "noah-028",
      "src": "/rewards/noah/noah-028.png"
    },
    {
      "id": "noah-029",
      "src": "/rewards/noah/noah-029.png"
    },
    {
      "id": "noah-030",
      "src": "/rewards/noah/noah-030.png"
    },
    {
      "id": "noah-031",
      "src": "/rewards/noah/noah-031.png"
    },
    {
      "id": "noah-032",
      "src": "/rewards/noah/noah-032.png"
    },
    {
      "id": "noah-033",
      "src": "/rewards/noah/noah-033.png"
    },
    {
      "id": "noah-034",
      "src": "/rewards/noah/noah-034.png"
    },
    {
      "id": "noah-035",
      "src": "/rewards/noah/noah-035.png"
    },
    {
      "id": "noah-036",
      "src": "/rewards/noah/noah-036.png"
    },
    {
      "id": "noah-037",
      "src": "/rewards/noah/noah-037.png"
    },
    {
      "id": "noah-038",
      "src": "/rewards/noah/noah-038.png"
    },
    {
      "id": "noah-039",
      "src": "/rewards/noah/noah-039.png"
    },
    {
      "id": "noah-040",
      "src": "/rewards/noah/noah-040.png"
    },
    {
      "id": "noah-041",
      "src": "/rewards/noah/noah-041.png"
    },
    {
      "id": "noah-042",
      "src": "/rewards/noah/noah-042.png"
    },
    {
      "id": "noah-043",
      "src": "/rewards/noah/noah-043.png"
    },
    {
      "id": "noah-044",
      "src": "/rewards/noah/noah-044.png"
    },
    {
      "id": "noah-045",
      "src": "/rewards/noah/noah-045.png"
    },
    {
      "id": "noah-046",
      "src": "/rewards/noah/noah-046.png"
    }
  ],
  "super-heros": [
    {
      "id": "super-heros-001",
      "src": "/rewards/super-heros/super-heros-001.webp"
    },
    {
      "id": "super-heros-002",
      "src": "/rewards/super-heros/super-heros-002.webp"
    },
    {
      "id": "super-heros-003",
      "src": "/rewards/super-heros/super-heros-003.webp"
    },
    {
      "id": "super-heros-004",
      "src": "/rewards/super-heros/super-heros-004.webp"
    },
    {
      "id": "super-heros-005",
      "src": "/rewards/super-heros/super-heros-005.webp"
    },
    {
      "id": "super-heros-006",
      "src": "/rewards/super-heros/super-heros-006.webp"
    },
    {
      "id": "super-heros-007",
      "src": "/rewards/super-heros/super-heros-007.webp"
    },
    {
      "id": "super-heros-008",
      "src": "/rewards/super-heros/super-heros-008.webp"
    },
    {
      "id": "super-heros-009",
      "src": "/rewards/super-heros/super-heros-009.webp"
    },
    {
      "id": "super-heros-010",
      "src": "/rewards/super-heros/super-heros-010.webp"
    },
    {
      "id": "super-heros-011",
      "src": "/rewards/super-heros/super-heros-011.webp"
    },
    {
      "id": "super-heros-012",
      "src": "/rewards/super-heros/super-heros-012.webp"
    },
    {
      "id": "super-heros-013",
      "src": "/rewards/super-heros/super-heros-013.webp"
    },
    {
      "id": "super-heros-014",
      "src": "/rewards/super-heros/super-heros-014.webp"
    },
    {
      "id": "super-heros-015",
      "src": "/rewards/super-heros/super-heros-015.webp"
    },
    {
      "id": "super-heros-016",
      "src": "/rewards/super-heros/super-heros-016.webp"
    },
    {
      "id": "super-heros-017",
      "src": "/rewards/super-heros/super-heros-017.webp"
    },
    {
      "id": "super-heros-018",
      "src": "/rewards/super-heros/super-heros-018.webp"
    },
    {
      "id": "super-heros-019",
      "src": "/rewards/super-heros/super-heros-019.webp"
    },
    {
      "id": "super-heros-020",
      "src": "/rewards/super-heros/super-heros-020.webp"
    },
    {
      "id": "super-heros-021",
      "src": "/rewards/super-heros/super-heros-021.webp"
    },
    {
      "id": "super-heros-022",
      "src": "/rewards/super-heros/super-heros-022.webp"
    },
    {
      "id": "super-heros-023",
      "src": "/rewards/super-heros/super-heros-023.webp"
    },
    {
      "id": "super-heros-024",
      "src": "/rewards/super-heros/super-heros-024.webp"
    },
    {
      "id": "super-heros-025",
      "src": "/rewards/super-heros/super-heros-025.webp"
    },
    {
      "id": "super-heros-026",
      "src": "/rewards/super-heros/super-heros-026.webp"
    },
    {
      "id": "super-heros-027",
      "src": "/rewards/super-heros/super-heros-027.webp"
    },
    {
      "id": "super-heros-028",
      "src": "/rewards/super-heros/super-heros-028.webp"
    },
    {
      "id": "super-heros-029",
      "src": "/rewards/super-heros/super-heros-029.webp"
    },
    {
      "id": "super-heros-030",
      "src": "/rewards/super-heros/super-heros-030.webp"
    }
  ]
}
